name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docker-Compose Remote Deployment
        uses: alex-ac/github-action-ssh-docker-compose@master
        with:
          ssh_host: ${{ secrets.SERVER_HOSTNAME }} 
          ssh_private_key: ${{ secrets.SERVER_TEST_SSH_KEY }}
          ssh_user: ${{ secrets.SERVER_SSH_USER }}
