name: Deploy

on:
  push:
    branches: [ main ]
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.SERVER_HOSTNAME }} 
        ssh_private_key: ${{ secrets.SERVER_TEST_SSH_KEY }}
        ssh_user: ${{ secrets.SERVER_SSH_USER }}
        docker_compose_filename: docker-compose.yaml
